### ISSUE TITLE
Improved upward traversal of Feature tree

### ISSUE THREAD

**Issue by DarioRomano** [Universal-Variability-Language/uvl-parser#4]
For ease of use when building a feature tree programmatically without direct use of the parser, it would be nice to have a function to easily access the parent-Feature of a given Feature.
A method `public Feature getParent();` would be nice to have for the [Feature](https://github.com/Universal-Variability-Language/uvl-parser2.0/blob/main/src/main/java/de/vill/model/Feature.java) class.

**Comment by st-vi** [comment]
Thanks for your feedback. We added the functionality you requested.
