### ISSUE TITLE
Mismatch in the grammar and toString() of the FeatureModel

### ISSUE THREAD

**Issue by prankuragarwal** [Universal-Variability-Language/uvl-parser#8]
Acc. to the [grammar](https://github.com/Universal-Variability-Language/uvl-parser2.0/blob/ffb66a17de165d4d58e94e08d0da575469559699/src/main/antlr4/de/vill/UVL.g4#L95) of FeatureModel, it should start with namespace (if there is any) then includes then other things. But in the toString() [function](https://github.com/Universal-Variability-Language/uvl-parser2.0/blob/ffb66a17de165d4d58e94e08d0da575469559699/src/main/java/de/vill/model/FeatureModel.java#L294) it has includes first and then namespace. What's happening is that when I write a feature model to a file and then read that file again, it gives a parsing error.

**Comment by SundermannC** [comment]
Thanks a lot for the detailed report, @prankuragarwal
The grammar describes the structure as intended, the problem here is the toString() function.
We will fix this.
